// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOBft8SLoFsmBlFbYPcy0AM_ytdvqwno',
    appId: '1:106956907630:web:0c78471ed39e0648a7327f',
    messagingSenderId: '106956907630',
    projectId: 'summerhacks7',
    authDomain: 'summerhacks7.firebaseapp.com',
    storageBucket: 'summerhacks7.firebasestorage.app',
    measurementId: 'G-HHH3M576DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrfqDW1ySaSTuiNpbWF5r0fWwouS2rYB0',
    appId: '1:106956907630:android:acd79e3d8c3be63da7327f',
    messagingSenderId: '106956907630',
    projectId: 'summerhacks7',
    storageBucket: 'summerhacks7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW6P6P6K919km7Tneoy5f0f5mnDBPC8bI',
    appId: '1:106956907630:ios:7a286bf5b3759d8fa7327f',
    messagingSenderId: '106956907630',
    projectId: 'summerhacks7',
    storageBucket: 'summerhacks7.firebasestorage.app',
    iosBundleId: 'com.example.summerhack',
  );
}
